name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
          
      - name: Build with Next.js
        run: |
          echo "Starting Next.js build for static export..."
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Environment: NODE_ENV=$NODE_ENV"
          export NODE_ENV=production
          echo "Set NODE_ENV to: $NODE_ENV"
          
          echo "Installing dependencies..."
          npm ci
          
          echo "Running Next.js build..."
          npm run build 2>&1 | tee build.log
          BUILD_EXIT_CODE=${PIPESTATUS[0]}
          echo "Build exit code: $BUILD_EXIT_CODE"
          
          if [ $BUILD_EXIT_CODE -eq 0 ]; then
            echo "✅ Build succeeded"
          else
            echo "❌ Build failed, showing error log:"
            cat build.log
            echo "Trying alternative build approach..."
            npx next build --debug 2>&1 | tee debug-build.log || echo "Debug build also failed"
          fi
          
          echo "Checking output..."
          pwd
          ls -la
          
          echo "Looking for out directory..."
          if [ -d "out" ]; then
            echo "✅ out directory found"
            echo "Contents of out directory:"
            ls -la out/
            echo "Total files in out:"
            find out -type f | wc -l
            echo "Adding .nojekyll file for GitHub Pages..."
            touch out/.nojekyll
            echo "Checking for index.html..."
            if [ -f "out/index.html" ]; then
              echo "✅ index.html found"
              echo "First 50 lines of index.html:"
              head -50 out/index.html
            else
              echo "❌ index.html not found in out directory"
              find out -name "*.html" | head -10
            fi
          else
            echo "❌ out directory not found - creating fallback"
            echo "Available directories:"
            ls -la
            echo "Checking .next directory:"
            if [ -d ".next" ]; then
              ls -la .next/
              find .next -name "*.html" | head -5
            fi
            echo "Creating manual out directory..."
            mkdir -p out
            cat > out/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>NULL EEC Terminal - Build Failed</title>
            <style>
              body { font-family: monospace; background: black; color: #00ff00; padding: 20px; }
              .error { color: #ff0000; }
              .info { color: #0099ff; }
            </style>
          </head>
          <body>
            <h1>NULL EEC Terminal</h1>
            <p class="error">Build failed - using fallback page</p>
            <p class="info">Check GitHub Actions logs for details</p>
            <p>Repository: <a href="https://github.com/CSivakesav/NULL-EEC-Terminal">NULL-EEC-Terminal</a></p>
          </body>
          </html>
          EOF
            touch out/.nojekyll
          fi
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4