name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build with Next.js
        run: |
          echo "Starting Next.js build for static export..."
          npm run build
          echo "Build completed. Checking output..."
          pwd
          ls -la
          echo "Looking for out directory..."
          if [ -d "out" ]; then
            echo "✅ out directory found"
            echo "Contents of out directory:"
            ls -la out/
            echo "Total files in out:"
            find out -type f | wc -l
            echo "Adding .nojekyll file for GitHub Pages..."
            touch out/.nojekyll
            echo "Checking for index.html..."
            if [ -f "out/index.html" ]; then
              echo "✅ index.html found"
            else
              echo "❌ index.html not found"
              ls -la out/
            fi
          else
            echo "❌ out directory not found"
            echo "Checking for build artifacts..."
            ls -la .next/ || echo "No .next directory"
            echo "Trying alternative export location..."
            # Some Next.js configurations may output to different locations
            find . -name "*.html" -o -name "index.html" | head -10
            echo "Creating fallback out directory with current build..."
            mkdir -p out
            # If static files exist elsewhere, try to copy them
            if [ -d ".next/static" ]; then
              cp -r .next/static out/ || echo "Could not copy static files"
            fi
            if [ -f ".next/server/pages/index.html" ]; then
              cp .next/server/pages/index.html out/ || echo "Could not copy index.html"
            fi
            touch out/.nojekyll
          fi
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4